name: Lint package definitions
on:
  pull_request:
  merge_group:
permissions:
  contents: read
jobs:
  ast-grep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup Nix
        uses: NixOS/nix-installer-action@main
      - name: Run ast-grep lint rules
        run: nix build --print-build-logs '.#checks.x86_64-linux.ast-grep'
      - name: Check package metadata completeness
        run: nix build --print-build-logs '.#checks.x86_64-linux.meta-completeness'
